# Generated by Django 5.0.2 on 2024-05-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversationmessage",
            old_name="sent_by",
            new_name="created_by",
        ),
    ]
