# Generated by Django 5.0.2 on 2024-05-21 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_reservation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="quests",
            new_name="guests",
        ),
    ]
