# Generated by Django 5.0.2 on 2024-05-22 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_rename_quests_reservation_guests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="favourited",
            field=models.ManyToManyField(
                blank=True, related_name="favourites", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
